"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const objectStorage_1 = require("../src/common/objectStorage");
const graphBlock_1 = require("../src/codeGen/graphBlock");
const printNode_1 = require("../src/codeGen/printNode");
const pyCodeGen_1 = require("../src/codeGen/pyCodeGen");
objectStorage_1.Database.fromJSON(JSON.parse((0, fs_1.readFileSync)("response.json", 'utf-8')));
const graph = new graphBlock_1.LayerGraph();
// graph.initFromJSON(JSON.parse(readFileSync("graph.json", "utf-8")));
// writeFileSync("rewritenGraph.json", JSON.stringify(graph.toJSON(), null, 4));
graph.initFromJSON(JSON.parse((0, fs_1.readFileSync)("rewritenGraph.json", "utf-8")));
// writeFileSync("codeGen.json", JSON.stringify(genPython(graph), null, 4));
(0, fs_1.writeFileSync)("generatedCode.py", (0, printNode_1.printNode)((0, pyCodeGen_1.genPython)(graph)));
